version: "3.9"
services:
# ====================================================================================================================
# POSTGRES SERVER
# ====================================================================================================================
  pg-docker:
    image: postgres:latest
    restart: unless-stopped
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: supportServiceDB
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - /.data/postgresql/data:/etc/postgresql/data
    networks:
      - dev-network
# ====================================================================================================================
# PGADMIN
# ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - /home/Frank/IdeaProjects/SupportService-v3.0/back/docker/.data/pgadmin:/etc/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
# ====================================================================================================================
# PROMETHEUS
# ====================================================================================================================
  prometheus-supportService:
    image: prom/prometheus:latest
    container_name: prometheus-supportService
    networks:
      - dev-network
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - "9091:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    user: root
    restart: unless-stopped
# ====================================================================================================================
# GRAFANA
# ====================================================================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-supportService
    networks:
      - dev-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus-supportService
# ======================================================================================================================
# NETWORK
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge

volumes:
  grafana-storage:
