cors:
    origins: "*"
email:
    password-recover:
        token:
            minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:30}
        uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/recover-password/}
security:
    client-id: ${CLIENT_ID:SupportServiceApp}
    client-secret: ${CLIENT_SECRET:SupportServiceAppPassword}
    jwt:
        duration: ${JWT_DURATION:86400}
server:
    port: 8081
spring:
    jpa:
        open-in-view: false
        show-sql: true
    output:
        ansi:
            enabled: ALWAYS
    hibernate:
        jdbc:
            time_zone: UTC
    mail:
        host: ${EMAIL_HOST:smtp.gmail.com}
        password: ${EMAIL_PASSWORD:1234567}
        port: ${EMAIL_PORT:587}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: ${EMAIL_USERNAME:teste@gmail.com}
    profiles:
        active: ${APP_PROFILE:test}
springdoc:
    api-docs:
        path: /api-doc
logging:
    level:
        org.hibernate.SQL: DEBUG
