cors:
    origins: "*"
email:
    password-recover:
        token:
            minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:30}
        uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/recover-password/}
security:
    client-id: ${CLIENT_ID:SupportServiceApp}
    client-secret: ${CLIENT_SECRET:SupportServiceAppPassword}
    jwt:
        duration: ${JWT_DURATION:86400}
server:
    port: 8081

spring:
    jpa:
        open-in-view: false
        show-sql: true
    output:
        ansi:
            enabled: ALWAYS

    hibernate:
        jdbc:
            time_zone: UTC
    mail:
        host: ${EMAIL_HOST:smtp.gmail.com}
        password: ${EMAIL_PASSWORD:1234567}
        port: ${EMAIL_PORT:587}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: ${EMAIL_USERNAME:teste@gmail.com}
    profiles:
        active: ${APP_PROFILE:test}

springdoc:
    api-docs:
        path: /supportService/v3/api-docs
    swagger-ui:
        operationsSorter: method
        path: /swagger-ui.html
        title: "REST Documentation for SupportService API "
        description: "This is the REST UI support of SupportService API. Here you can perform REST operations on the API."
        license: "Apache License 2.0"
        base_package: "com.dev.ServiceHelp"
        contact_name: "Frank Destro"
        contact_url: "https://github.com/FrankDestro/SupportService-v3.0"
        contact_email: "frank-destro@outlook.com"
logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: refresh, health, info, metrics, prometheus, h2-console
    endpoint:
        health:
            enabled: true
            show-details : always
        info:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled : true




