spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/supportServiceDB
    username: postgres
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  # Uncomment the following lines if needed for schema generation
  # properties:
  #   jakarta:
  #     persistence:
  #       schema-generation:
  #         create-source: metadata
  #         scripts:
  #           action: create
  #           create-target: newSql.sql
  #   hibernate:
  #     hbm2ddl:
  #       delimiter: ";"
