export const data = [
    {
      id: 1,
      title: 'Chamado 1',
      description: 'Problema no servidor',
      requester: 'João Silva',
      status: 'Andamento',
      priority: 'Alta',
      type: 'Hardware',
      openingDate: '2024-01-31',
      dueDate: '2024-02-10',
      responsavel: 'Técnico1', 
    },
    {
      id: 2,
      title: 'Chamado 2',
      description: 'Problema com software de email',
      requester: 'Maria Oliveira',
      status: 'Aberto',
      priority: 'Média',
      type: 'Software',
      openingDate: '2024-02-01',
      dueDate: '2024-02-15',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 3,
      title: 'Chamado 3',
      description: 'Problema com impressora',
      requester: 'Carlos Santos',
      status: 'Cancelado',
      priority: 'Baixa',
      type: 'Hardware',
      openingDate: '2024-02-05',
      dueDate: '2024-02-20',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
  
    {
      id: 4,
      title: 'Chamado 4',
      description: 'Problema na rede interna',
      requester: 'Ana Lima',
      status: 'Andamento',
      priority: 'Média',
      type: 'Networking',
      openingDate: '2024-02-10',
      dueDate: '2024-02-25',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 5,
      title: 'Chamado 5',
      description: 'Problema com sistema operacional',
      requester: 'Fernando Silva',
      status: 'Aberto',
      priority: 'Alta',
      type: 'Software',
      openingDate: '2024-02-15',
      dueDate: '2024-03-01',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 6,
      title: 'Chamado 6',
      description: 'Problema no acesso remoto',
      requester: 'Gabriel Oliveira',
      status: 'Cancelado',
      priority: 'Baixa',
      type: 'Networking',
      openingDate: '2024-02-20',
      dueDate: '2024-03-05',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 7,
      title: 'Chamado 7',
      description: 'Problema no software de contabilidade',
      requester: 'Mariana Costa',
      status: 'Aberto',
      priority: 'Média',
      type: 'Software',
      openingDate: '2024-02-25',
      dueDate: '2024-03-10',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 8,
      title: 'Chamado 8',
      description: 'Problema no servidor de arquivos',
      requester: 'Ricardo Santos',
      status: 'Andamento',
      priority: 'Alta',
      type: 'Hardware',
      openingDate: '2024-03-01',
      dueDate: '2024-03-15',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 9,
      title: 'Chamado 9',
      description: 'Problema com impressora colorida',
      requester: 'Carla Mendes',
      status: 'Cancelado',
      priority: 'Baixa',
      type: 'Hardware',
      openingDate: '2024-03-05',
      dueDate: '2024-03-20',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 10,
      title: 'Chamado 10',
      description: 'Problema na atualização do antivírus',
      requester: 'Pedro Oliveira',
      status: 'Aberto',
      priority: 'Média',
      type: 'Software',
      openingDate: '2024-03-10',
      dueDate: '2024-03-25',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 11,
      title: 'Chamado 11',
      description: 'Problema no sistema de backup',
      requester: 'Fernanda Lima',
      status: 'Andamento',
      priority: 'Alta',
      type: 'Software',
      openingDate: '2024-03-15',
      dueDate: '2024-03-30',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 12,
      title: 'Chamado 12',
      description: 'Problema no acesso VPN',
      requester: 'Lucas Oliveira',
      status: 'Cancelado',
      priority: 'Baixa',
      type: 'Networking',
      openingDate: '2024-03-20',
      dueDate: '2024-04-05',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 13,
      title: 'Chamado 13',
      description: 'Problema com driver de impressora',
      requester: 'Juliana Santos',
      status: 'Aberto',
      priority: 'Média',
      type: 'Hardware',
      openingDate: '2024-03-25',
      dueDate: '2024-04-10',
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 14,
      title: "Chamado 14",
      description: "Problema com conexão de rede",
      requester: "Carlos Silva",
      status: "Aberto",
      priority: "Alta",
      type: "Rede",
      openingDate: "2024-03-26",
      dueDate: "2024-04-12",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 15,
      title: "Chamado 15",
      description: "Software travando frequentemente",
      requester: "Ana Oliveira",
      status: "Aberto",
      priority: "Baixa",
      type: "Software",
      openingDate: "2024-03-27",
      dueDate: "2024-04-14",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 16,
      title: "Chamado 16",
      description: "Problema com periféricos USB",
      requester: "Rafael Costa",
      status: "Aberto",
      priority: "Média",
      type: "Hardware",
      openingDate: "2024-03-28",
      dueDate: "2024-04-16",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 17,
      title: "Chamado 17",
      description: "Solicitação de atualização de software",
      requester: "Mariana Lima",
      status: "Aberto",
      priority: "Baixa",
      type: "Software",
      openingDate: "2024-03-29",
      dueDate: "2024-04-18",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 18,
      title: "Chamado 18",
      description: "Problema com login no sistema",
      requester: "Lucas Rodrigues",
      status: "Aberto",
      priority: "Alta",
      type: "Software",
      openingDate: "2024-03-30",
      dueDate: "2024-04-20",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 19,
      title: "Chamado 19",
      description: "Solicitação de configuração de e-mail",
      requester: "Patricia Santos",
      status: "Aberto",
      priority: "Média",
      type: "Software",
      openingDate: "2024-03-31",
      dueDate: "2024-04-22",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 20,
      title: "Chamado 20",
      description: "Problema com tela piscando",
      requester: "Gabriel Oliveira",
      status: "Aberto",
      priority: "Baixa",
      type: "Hardware",
      openingDate: "2024-04-01",
      dueDate: "2024-04-24",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 21,
      title: "Chamado 21",
      description: "Solicitação de instalação de software",
      requester: "Fernanda Silva",
      status: "Aberto",
      priority: "Média",
      type: "Software",
      openingDate: "2024-04-02",
      dueDate: "2024-04-26",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },
    {
      id: 22,
      title: "Chamado 22",
      description: "Problema com acesso a arquivos compartilhados",
      requester: "Eduardo Costa",
      status: "Aberto",
      priority: "Alta",
      type: "Rede",
      openingDate: "2024-04-03",
      dueDate: "2024-04-28",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    },{
      id: 23,
      title: "Chamado 23",
      description: "Solicitação de suporte para impressora",
      requester: "Amanda Lima",
      status: "Aberto",
      priority: "Baixa",
      type: "Hardware",
      openingDate: "2024-04-04",
      dueDate: "2024-04-30",
      responsavel: 'Técnico1', // Adicionei o campo "responsavel" com o nome do técnico
    }
  ];